const https = require('https');

// Gemini API configuration - Add your API key to config file or environment variable
const GEMINI_API_KEY = process.env.GEMINI_API_KEY || require('../data/config').geminiApiKey;

// Function to make Gemini API request
async function getGeminiResponse(question) {
    return new Promise((resolve, reject) => {
        const prompt = `You are a pessimistic Magic 8-Ball oracle. Someone has asked you: "${question}"

You must respond with exactly 5 words or fewer. Your response must ALWAYS be negative, discouraging, or the opposite of what the user would want to hear.

Rules:
- Maximum 5 words
- Always negative/pessimistic
- Crush their hopes
- Give the worst possible answer
- Be definitively discouraging

Examples:
- "No, never will happen."
- "Absolutely not, forget it."
- "Terrible idea, don't try."
- "No chance at all."
- "Disaster awaits, avoid completely."

Now respond to their question with maximum negativity in 5 words or less:`;

        const requestData = JSON.stringify({
            contents: [{
                parts: [{
                    text: prompt
                }]
            }],
            generationConfig: {
                temperature: 0.9,
                topK: 1,
                topP: 1,
                maxOutputTokens: 100
            },
            safetySettings: [
                {
                    category: "HARM_CATEGORY_SEXUALLY_EXPLICIT",
                    threshold: "BLOCK_MEDIUM_AND_ABOVE"
                },
                {
                    category: "HARM_CATEGORY_DANGEROUS_CONTENT",
                    threshold: "BLOCK_MEDIUM_AND_ABOVE"
                }
            ]
        });

        const options = {
            hostname: 'generativelanguage.googleapis.com',
            path: `/v1beta/models/gemini-2.5-flash-latest:generateContent?key=${GEMINI_API_KEY}`,
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Content-Length': Buffer.byteLength(requestData)
            }
        };

        const req = https.request(options, (res) => {
            let data = '';
            res.on('data', (chunk) => {
                data += chunk;
            });
            res.on('end', () => {
                console.log('Raw Gemini API response:', data); // Debug logging
                
                try {
                    const response = JSON.parse(data);
                    
                    // Check for API errors
                    if (response.error) {
                        console.error('Gemini API error:', response.error);
                        reject(new Error(`Gemini API error: ${response.error.message || 'Unknown error'}`));
                        return;
                    }
                    
                    // Check for content filtering/safety blocks
                    if (response.candidates && response.candidates[0] && response.candidates[0].finishReason === 'SAFETY') {
                        reject(new Error('Response was blocked by safety filters'));
                        return;
                    }
                    
                    // Extract the generated text
                    if (response.candidates && 
                        response.candidates[0] && 
                        response.candidates[0].content && 
                        response.candidates[0].content.parts && 
                        response.candidates[0].content.parts[0] && 
                        response.candidates[0].content.parts[0].text) {
                        
                        const generatedText = response.candidates[0].content.parts[0].text.trim();
                        resolve(generatedText);
                    } else {
                        console.error('Unexpected response structure:', JSON.stringify(response, null, 2));
                        reject(new Error('No valid response generated by Gemini API'));
                    }
                } catch (parseError) {
                    console.error('Failed to parse API response:', parseError);
                    console.error('Raw response data:', data);
                    reject(new Error('Failed to parse Gemini API response'));
                }
            });
        });

        req.on('error', (error) => {
            console.error('HTTPS request error:', error);
            reject(new Error(`Network error: ${error.message}`));
        });

        // Handle request timeout
        req.setTimeout(10000, () => {
            req.destroy();
            reject(new Error('Request timeout'));
        });

        req.write(requestData);
        req.end();
    });
}

// Fallback responses if API fails
const fallbackResponses = [
    "The mystical forces are currently disrupted... Try asking again in a moment.",
    "The cosmic energies are realigning... Ask your question again shortly.",
    "The oracle's connection to the spirit realm is temporarily clouded... Please try again.",
    "The ancient magic is recharging... Your answer awaits, ask again soon.",
    "The mystical network is experiencing interference... Try once more."
];

module.exports = (client) => {
    console.log('🎱 Magic 8-Ball Handler (Gemini AI) initialized');

    // Handle magic 8-ball command
    client.on('messageCreate', async (message) => {
        if (message.author.bot) return;
        if (!message.guild) return;

        const args = message.content.split(' ');
        const command = args[0].toLowerCase();

        // Magic 8-Ball command
        if (command === '!ask' || command === '!8ball' || command === '!magic8ball') {
            // Check if user provided a question
            const question = args.slice(1).join(' ');
            
            if (!question || question.trim().length === 0) {
                return message.reply('🎱 Please ask me a question! Example: `!ask Will I have a good day?`');
            }

            // Limit question length
            if (question.length > 200) {
                return message.reply('❌ Please keep your question under 200 characters.');
            }

            // Check if API key is configured
            if (!GEMINI_API_KEY) {
                return message.reply('❌ The magic 8-ball oracle is not properly configured. Please contact an administrator.');
            }

            try {
                console.log(`🎱 ${message.author.tag} asked: "${question}"`);

                // Get AI-generated response
                let response;
                try {
                    response = await getGeminiResponse(question);
                    console.log(`🤖 Gemini response: "${response}"`);
                } catch (apiError) {
                    console.error('Gemini API error details:', apiError.message);
                    // Use fallback response
                    response = fallbackResponses[Math.floor(Math.random() * fallbackResponses.length)];
                    console.log(`🔄 Using fallback response: "${response}"`);
                }

                // Simple response with magic 8-ball emoji
                return message.reply(`🎱 ${response}`);

            } catch (error) {
                console.error('Error handling magic 8-ball command:', error);
                return message.reply('❌ The mystical forces are currently disrupted. Please try again later!');
            }
        }

        // Test command for debugging API connection
        if (command === '!8balltest') {
            // Check if user has administrator permissions
            if (!message.member.permissions.has('Administrator')) {
                return message.reply("❌ You need Administrator permissions to test the API connection.");
            }

            if (!GEMINI_API_KEY) {
                return message.reply('❌ No API key configured. Please set GEMINI_API_KEY environment variable or add geminiApiKey to config.');
            }

            try {
                const testResponse = await getGeminiResponse("Is this API working?");
                return message.reply(`✅ API test successful! Response: "${testResponse}"`);
            } catch (error) {
                return message.reply(`❌ API test failed: ${error.message}`);
            }
        }
    });
};